name: Manually Build Calendars

on: workflow_dispatch

jobs:
  build-calendars:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pip install
      uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt

    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Cargo run
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --release

    - name: Write current time stamp to GH variable
      id: date
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%dT%H:%M')"

    - name: List all calendars to GH variable
      run: echo "::set-output name=LS_CALENDARS::$(ls calendars/* | xargs echo | sed 's/ /,/g')"
      id: LS-CALENDARS

    - name: Update latest release with new calendars
      uses: beyarkay/update-existing-release@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release: Latest Eskom Loadshedding Calendars
        updateTag: true
        tag: latest
        replace: true
        files: ${{ steps.LS-CALENDARS.outputs.LS_CALENDARS }}
        body: "To get your loadshedding schedule in your calendar you should

          1. scroll down to the blue links under `Assets`

          2. Find the `ics` calendar file corresponding to your area

          3. Right-click on the file and copy the link

          4. Open your calendar app (Google Calendar, Outlook, Apple Calendar, etc)

          5. Paste the calendar link in your app's `subscribe to calendar` option.


          That's it! Now you've got loadshedding warning in your calendar that
          tell you if the power will be off or not. This is better than apps
          like EskomSePush because it combines what area you're in with your
          area's loadshedding schedule.

          You'll only be notified if


          1. there's national loadshedding announced by Eskom and

          2. your area has loadshedding scheduled for that time.

          It's also open source! We depend on pull requests to update
          `manually_specified.yaml` with the latest schedule. Please submit a
          PR if Eskom announces a change!


          Last updated: ${{ steps.date.outputs.datetime }}"

