name: Check Python Formatting

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/parse_city_power.py'
      - 'src/parse_coct_html.py'
      - 'src/parse_eskom.py'
      - 'src/parse_ekurhuleni.py'
  pull_request:
    branches: [ "main" ]   
    paths:
      - 'src/parse_city_power.py'
      - 'src/parse_coct_html.py'
      - 'src/parse_eskom.py'
      - 'src/parse_ekurhuleni.py'

  workflow_dispatch:

jobs:
  python-format-check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Check *.py for formatting errors with black"
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "src/parse_city_power.py src/parse_coct_html.py src/parse_eskom.py src/parse_ekurhuleni.py --check"
