name: Check Rust Formatting

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/main.rs'
      - 'src/structs.rs'
  pull_request:
    branches: [ "main" ]   
    paths:
      - 'src/main.rs'
      - 'src/structs.rs'

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-format-check:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup rustfmt
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt

    - name: Check rust files for formatting errors
      uses: actions-rust-lang/rustfmt@v1

